# Generated by Django 4.0.2 on 2022-02-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChesscomGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=30, null=True)),
                ('user_white', models.IntegerField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('time_control', models.CharField(blank=True, max_length=10, null=True)),
                ('moves', models.CharField(blank=True, max_length=2000, null=True)),
                ('white_won', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chesscom_games',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=30, null=True)),
                ('rapid', models.IntegerField(blank=True, null=True)),
                ('blitz', models.IntegerField(blank=True, null=True)),
                ('bullet', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_ratings',
                'managed': False,
            },
        ),
    ]
